// Kentucky Derby 152 — Media Center Seating PWA
// Service Worker — auto-generated by generate_all.py
// Cache version bumped automatically on every pipeline run
const CACHE = 'kd152-20260403-0955';

// Files to pre-cache on install
const PRECACHE = [
  './',
  './index.html',
  './manifest.json'
];

// Install: cache all core assets
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      .then(cache => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

// Activate: purge old caches
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys.filter(k => k !== CACHE).map(k => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

// Fetch: cache-first for same-origin, with background update
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin === location.origin) {
    event.respondWith(
      caches.match(event.request).then(cached => {
        if (cached) {
          fetch(event.request).then(r => {
            if (r && r.status === 200)
              caches.open(CACHE).then(c => c.put(event.request, r));
          }).catch(() => {});
          return cached;
        }
        return fetch(event.request).then(r => {
          if (r && r.status === 200)
            caches.open(CACHE).then(c => c.put(event.request, r.clone()));
          return r;
        }).catch(() => caches.match('./index.html'));
      })
    );
  }
});

// Allow the page to trigger a SW swap
self.addEventListener('message', event => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});
